#!/bin/bash

sudo cp bin/linux/heartbeat.sh /usr/local/bin/heartbeat
sudo cp files/etc/systemd/mysql-heartbeat.service /etc/systemd/system/

mysql -uci -pci -h 127.0.0.1 --port 10111 test < sql/heartbeat.sql
