#!/bin/bash

[ -f bin/linux/dbdeployer.gz ] && (cd bin/linux ; gunzip dbdeployer.gz)

~/sandboxes/57/stop_all || :
dbdeployer delete 57 || :
sudo rm -rf ~/sandboxes/57 || :

mkdir -p ~/opt/mysql
bin/linux/dbdeployer unpack mysql-tarballs/mysql-5.7.26.tar.xz
bin/linux/dbdeployer deploy replication 5.7.26 \
  --sandbox-directory="57" \
  --base-port=10570 \
  -n 4 \
  --gtid \
  --repl-crash-safe \
  --pre-grants-sql="grant all on *.* to ci@'%' identified by 'ci'" \
  --my-cnf-options="report_host=127.0.0.1" \
  --my-cnf-options="bind_address=0.0.0.0" \
  --my-cnf-options="log_bin" \
  --my-cnf-options="log_slave_updates" \
  --my-cnf-options="performance_schema=0" \
  --my-cnf-options="innodb_buffer_pool_size=32M"
  --my-cnf-options="read_only=1"
~/sandboxes/57/m -e "set global read_only=0"
