#!/bin/bash

[ -f bin/linux/dbdeployer.gz ] && (cd bin/linux ; gunzip dbdeployer.gz)

~/sandboxes/ci/stop_all || :
dbdeployer delete ci || :
sudo rm -rf ~/sandboxes/ci || :

mkdir -p ~/opt/mysql
bin/linux/dbdeployer unpack mysql-tarballs/mysql-5.7.26.tar.xz
bin/linux/dbdeployer deploy replication 5.7.26 \
  --sandbox-directory="ci" \
  --base-port=10110 \
  -n 4 \
  --gtid \
  --repl-crash-safe \
  --pre-grants-sql="grant all on *.* to ci@'%' identified by 'ci'" \
  --pre-grants-sql="grant all on test.* to heartbeat@'%' identified by 'heartbeat'" \
  --my-cnf-options="report_host=127.0.0.1" \
  --my-cnf-options="bind_address=0.0.0.0" \
  --my-cnf-options="log_bin" \
  --my-cnf-options="log_slave_updates" \
  --my-cnf-options="performance_schema=0" \
  --my-cnf-options="innodb_buffer_pool_size=32M" \
  --my-cnf-options="slave_net_timeout=2" \
  --my-cnf-options="read_only=1"
~/sandboxes/ci/m -e "set global read_only=0"
