#!/bin/bash

REPORT_HOSTNAME=${REPORT_HOSTNAME:-127.0.0.1}

script/run-consul
script/deploy-replication "$REPORT_HOSTNAME"
script/run-haproxy
script/run-consul-template
script/run-heartbeat

PATH=$PATH:~/opt/mysql/5.7.26/bin/

mysql -uci -pci -h 127.0.0.1 --port 10111 -s -s -e "select @@report_port"
mysql -uci -pci -h 127.0.0.1 --port 13306 -s -s -e "select @@report_port"
